CREATE ROLE web_anon NOLOGIN;

CREATE TABLE IF NOT EXISTS games (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    datestr TEXT NOT NULL,
    chipsperrub NUMERIC NOT NULL DEFAULT 0,
    mode TEXT NOT NULL DEFAULT 'cash',
    buyin NUMERIC NOT NULL DEFAULT 0,
    isclosed BOOLEAN NOT NULL DEFAULT FALSE,
    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS gameplayers (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    gameid BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    startchips NUMERIC NOT NULL DEFAULT 0,
    finalchips NUMERIC NOT NULL DEFAULT 0,
    diffrub NUMERIC NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fromname TEXT NOT NULL,
    toname TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    gameids TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_gameplayers_gameid ON gameplayers(gameid);
CREATE INDEX IF NOT EXISTS idx_games_createdat ON games(createdat DESC);

GRANT USAGE ON SCHEMA public TO web_anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO web_anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO web_anon;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO web_anon;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO web_anon;
